# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loaderrordialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadError(object):
    def setupUi(self, LoadError):
        LoadError.setObjectName("LoadError")
        LoadError.resize(460, 126)
        LoadError.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadError)
        self.buttonBox.setGeometry(QtCore.QRect(80, 90, 371, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditImagePath = QtWidgets.QLineEdit(LoadError)
        self.lineEditImagePath.setGeometry(QtCore.QRect(90, 50, 271, 20))
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.pushButtonBrowse = QtWidgets.QPushButton(LoadError)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(370, 50, 81, 23))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.label = QtWidgets.QLabel(LoadError)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label.setObjectName("label")
        self.lblError = QtWidgets.QLabel(LoadError)
        self.lblError.setGeometry(QtCore.QRect(10, 10, 431, 31))
        self.lblError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblError.setWordWrap(True)
        self.lblError.setObjectName("lblError")

        self.retranslateUi(LoadError)
        self.buttonBox.accepted.connect(LoadError.accept)
        self.buttonBox.rejected.connect(LoadError.reject)
        QtCore.QMetaObject.connectSlotsByName(LoadError)
        LoadError.setTabOrder(self.lineEditImagePath, self.pushButtonBrowse)
        LoadError.setTabOrder(self.pushButtonBrowse, self.buttonBox)

    def retranslateUi(self, LoadError):
        _translate = QtCore.QCoreApplication.translate
        LoadError.setWindowTitle(_translate("LoadError", "Freehand Raster Georeferencer - Image not found"))
        self.pushButtonBrowse.setText(_translate("LoadError", "Browse..."))
        self.label.setText(_translate("LoadError", "Image path"))
        self.lblError.setText(_translate("LoadError", "LabelError"))
