# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertiesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 340)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.groupBox_Style = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Style.sizePolicy().hasHeightForWidth())
        self.groupBox_Style.setSizePolicy(sizePolicy)
        self.groupBox_Style.setObjectName("groupBox_Style")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Style)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_Style)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_Transparency = QtWidgets.QSlider(self.groupBox_Style)
        self.horizontalSlider_Transparency.setMaximum(100)
        self.horizontalSlider_Transparency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Transparency.setObjectName("horizontalSlider_Transparency")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_Transparency)
        self.spinBox_Transparency = QtWidgets.QSpinBox(self.groupBox_Style)
        self.spinBox_Transparency.setMaximum(100)
        self.spinBox_Transparency.setObjectName("spinBox_Transparency")
        self.horizontalLayout_3.addWidget(self.spinBox_Transparency)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Style)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout_2.addWidget(self.groupBox_Style, 2, 0, 1, 1)
        self.groupBox_Properties = QtWidgets.QGroupBox(Dialog)
        self.groupBox_Properties.setObjectName("groupBox_Properties")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Properties)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_Properties = QtWidgets.QTextEdit(self.groupBox_Properties)
        self.textEdit_Properties.setReadOnly(True)
        self.textEdit_Properties.setTabStopWidth(80)
        self.textEdit_Properties.setObjectName("textEdit_Properties")
        self.gridLayout_3.addWidget(self.textEdit_Properties, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_Properties, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Properties"))
        self.groupBox_Style.setTitle(_translate("Dialog", "Style"))
        self.label.setText(_translate("Dialog", "Transparency"))
        self.label_4.setText(_translate("Dialog", "%"))
        self.groupBox_Properties.setTitle(_translate("Dialog", "Properties"))
