# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'freehandrastergeoreferencerdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FreehandRasterGeoreferencer(object):
    def setupUi(self, FreehandRasterGeoreferencer):
        FreehandRasterGeoreferencer.setObjectName("FreehandRasterGeoreferencer")
        FreehandRasterGeoreferencer.resize(464, 98)
        FreehandRasterGeoreferencer.setModal(True)
        self.lineEditImagePath = QtWidgets.QLineEdit(FreehandRasterGeoreferencer)
        self.lineEditImagePath.setGeometry(QtCore.QRect(90, 20, 271, 23))
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.pushButtonBrowse = QtWidgets.QPushButton(FreehandRasterGeoreferencer)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(370, 20, 81, 23))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.label = QtWidgets.QLabel(FreehandRasterGeoreferencer)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 23))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButtonAdd = QtWidgets.QPushButton(FreehandRasterGeoreferencer)
        self.pushButtonAdd.setEnabled(True)
        self.pushButtonAdd.setGeometry(QtCore.QRect(262, 58, 91, 30))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonCancel = QtWidgets.QPushButton(FreehandRasterGeoreferencer)
        self.pushButtonCancel.setEnabled(True)
        self.pushButtonCancel.setGeometry(QtCore.QRect(361, 59, 91, 29))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.toolButtonAdvanced = QtWidgets.QToolButton(FreehandRasterGeoreferencer)
        self.toolButtonAdvanced.setGeometry(QtCore.QRect(14, 63, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.toolButtonAdvanced.setFont(font)
        self.toolButtonAdvanced.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonAdvanced.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonAdvanced.setAutoRaise(True)
        self.toolButtonAdvanced.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonAdvanced.setObjectName("toolButtonAdvanced")

        self.retranslateUi(FreehandRasterGeoreferencer)
        QtCore.QMetaObject.connectSlotsByName(FreehandRasterGeoreferencer)
        FreehandRasterGeoreferencer.setTabOrder(self.lineEditImagePath, self.pushButtonBrowse)

    def retranslateUi(self, FreehandRasterGeoreferencer):
        _translate = QtCore.QCoreApplication.translate
        FreehandRasterGeoreferencer.setWindowTitle(_translate("FreehandRasterGeoreferencer", "Add raster for interactive georeferencing"))
        self.pushButtonBrowse.setText(_translate("FreehandRasterGeoreferencer", "Browse..."))
        self.label.setText(_translate("FreehandRasterGeoreferencer", "Image path"))
        self.pushButtonAdd.setText(_translate("FreehandRasterGeoreferencer", "Add New"))
        self.pushButtonCancel.setText(_translate("FreehandRasterGeoreferencer", "Cancel"))
        self.toolButtonAdvanced.setText(_translate("FreehandRasterGeoreferencer", "Advanced..."))
