# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportgeorefrasterdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportGeorefRasterDialog(object):
    def setupUi(self, ExportGeorefRasterDialog):
        ExportGeorefRasterDialog.setObjectName("ExportGeorefRasterDialog")
        ExportGeorefRasterDialog.resize(458, 119)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportGeorefRasterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(112, 81, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditImagePath = QtWidgets.QLineEdit(ExportGeorefRasterDialog)
        self.lineEditImagePath.setGeometry(QtCore.QRect(90, 10, 271, 20))
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.pushButtonBrowse = QtWidgets.QPushButton(ExportGeorefRasterDialog)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(370, 10, 81, 23))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.label = QtWidgets.QLabel(ExportGeorefRasterDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.checkBoxRotationMode = QtWidgets.QCheckBox(ExportGeorefRasterDialog)
        self.checkBoxRotationMode.setGeometry(QtCore.QRect(10, 40, 247, 17))
        self.checkBoxRotationMode.setObjectName("checkBoxRotationMode")
        self.checkBoxOnlyWorldFile = QtWidgets.QCheckBox(ExportGeorefRasterDialog)
        self.checkBoxOnlyWorldFile.setGeometry(QtCore.QRect(10, 65, 279, 17))
        self.checkBoxOnlyWorldFile.setObjectName("checkBoxOnlyWorldFile")

        self.retranslateUi(ExportGeorefRasterDialog)
        self.buttonBox.accepted.connect(ExportGeorefRasterDialog.accept)
        self.buttonBox.rejected.connect(ExportGeorefRasterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportGeorefRasterDialog)

    def retranslateUi(self, ExportGeorefRasterDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportGeorefRasterDialog.setWindowTitle(_translate("ExportGeorefRasterDialog", "Export georeferenced raster"))
        self.pushButtonBrowse.setText(_translate("ExportGeorefRasterDialog", "Browse..."))
        self.label.setText(_translate("ExportGeorefRasterDialog", "Image path"))
        self.checkBoxRotationMode.setToolTip(_translate("ExportGeorefRasterDialog", "<html><head/><body><p>If checked, the raster will be exported as is and the world file will contain the rotation, scaling and translation. Some GIS software may not be able to georeference the raster correctly in this mode. If unchecked, the raster will be modified with the rotation and the scaling between axis and the world file will contain the rest of the transformation.</p></body></html>"))
        self.checkBoxRotationMode.setText(_translate("ExportGeorefRasterDialog", "Put rotation in world file "))
        self.checkBoxOnlyWorldFile.setToolTip(_translate("ExportGeorefRasterDialog", "<html><head/><body><p>If checked, only the world file will be exported and the chosen file will not be overwritten. The rotation will be included in the world file.</p></body></html>"))
        self.checkBoxOnlyWorldFile.setText(_translate("ExportGeorefRasterDialog", "Only export world file for chosen raster"))
